CREATE USER TSK IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO TSK;
ALTER USER TSK QUOTA UNLIMITED ON USERS;

-- Chuyển context về schema TSK
ALTER SESSION SET CURRENT_SCHEMA=TSK;

-- Sequence
CREATE SEQUENCE TSK.SEQ_TASKS START WITH 1 INCREMENT BY 1;

-- Table
CREATE TABLE TSK.TASKS (
  ID NUMBER DEFAULT SEQ_TASKS.NEXTVAL PRIMARY KEY,
  NAME VARCHAR2(150),
  DESCRIPTION VARCHAR2(250),
  HAVEDONE NUMBER DEFAULT 0,
  CREATEDAT TIMESTAMP,
  UPDATEDAT TIMESTAMP,
  ENABLE NUMBER DEFAULT 1
);


-- Thêm dữ liệu mẫu
INSERT INTO TASKS (NAME, DESCRIPTION) VALUES ('Sample Task', 'This is a sample task');
